// Encode an RGBA8 buffer to disk. Format is chosen from the target path's
// extension; unknown extensions fall back to PNG.

use std::io::{Cursor, Write};
use std::path::Path;

use anyhow::{Context, Result};
use image::{ImageEncoder, ImageFormat, RgbaImage};

use crate::ops::resize::{resize_rgba, Filter};

/// Default ICO entry sizes used when `save_image` is asked to write a `.ico`
/// via the ordinary "save as" flow (i.e. without the dedicated multi-size
/// dialog). Covers every Windows shell surface from tray icons (16 px) up to
/// Jumbo icon view (256 px).
pub const DEFAULT_ICO_SIZES: [u32; 4] = [16, 32, 48, 256];

pub fn save_image(img: &RgbaImage, path: &Path) -> Result<()> {
    let format = format_from_path(path).unwrap_or(ImageFormat::Png);
    let dyn_img = image::DynamicImage::ImageRgba8(img.clone());
    match format {
        ImageFormat::Jpeg => {
            // JPEG has no alpha; collapse to RGB.
            dyn_img
                .to_rgb8()
                .save_with_format(path, ImageFormat::Jpeg)
                .with_context(|| format!("save jpeg {}", path.display()))?;
        }
        ImageFormat::Ico => {
            // `.ico` via generic save: write the standard 16/32/48/256 set so
            // Explorer renders correctly at every zoom level.
            save_as_ico(img, path, &DEFAULT_ICO_SIZES)
                .with_context(|| format!("save ico {}", path.display()))?;
        }
        f => {
            dyn_img
                .save_with_format(path, f)
                .with_context(|| format!("save {} {}", format_name(f), path.display()))?;
        }
    }
    Ok(())
}

pub fn format_from_path(path: &Path) -> Option<ImageFormat> {
    ImageFormat::from_path(path).ok()
}

fn format_name(f: ImageFormat) -> &'static str {
    match f {
        ImageFormat::Png => "png",
        ImageFormat::Jpeg => "jpeg",
        ImageFormat::WebP => "webp",
        ImageFormat::Gif => "gif",
        ImageFormat::Bmp => "bmp",
        ImageFormat::Tiff => "tiff",
        ImageFormat::Avif => "avif",
        ImageFormat::Ico => "ico",
        _ => "image",
    }
}

/// Write a multi-resolution Windows Icon file.
///
/// Each requested size is generated by high-quality Lanczos3 downscaling and
/// embedded as a PNG sub-entry. PNG-in-ICO has been universally supported on
/// Windows Vista and later, and results in a much smaller file than the
/// legacy DIB (BMP) encoding, especially for the 256-px entry.
///
/// Sizes are deduplicated, clamped to the 1..=256 range the ICO header can
/// express, and written in ascending order.
pub fn save_as_ico(img: &RgbaImage, path: &Path, sizes: &[u32]) -> Result<()> {
    if sizes.is_empty() {
        anyhow::bail!("no ICO sizes requested");
    }
    let mut sizes: Vec<u32> = sizes
        .iter()
        .copied()
        .filter(|s| (1..=256).contains(s))
        .collect();
    sizes.sort_unstable();
    sizes.dedup();
    if sizes.is_empty() {
        anyhow::bail!("all ICO sizes out of the 1..=256 range");
    }

    // Encode each requested size to PNG in memory; we need the blobs up
    // front so the directory entries can carry accurate offsets + sizes.
    let mut encoded: Vec<(u32, Vec<u8>)> = Vec::with_capacity(sizes.len());
    for size in &sizes {
        let resized = resize_rgba(img, *size, *size, Filter::Lanczos3)
            .with_context(|| format!("resize to {size}x{size} for ICO"))?;
        let mut png = Vec::new();
        image::codecs::png::PngEncoder::new(&mut png)
            .write_image(
                resized.as_raw(),
                resized.width(),
                resized.height(),
                image::ExtendedColorType::Rgba8,
            )
            .with_context(|| format!("encode png at {size}px"))?;
        encoded.push((*size, png));
    }

    let count = encoded.len() as u16;
    let header_size: u32 = 6 + 16 * count as u32; // ICONDIR + N * ICONDIRENTRY

    let mut out = Cursor::new(Vec::<u8>::with_capacity(
        header_size as usize
            + encoded.iter().map(|(_, d)| d.len()).sum::<usize>(),
    ));

    // ICONDIR header.
    out.write_all(&0u16.to_le_bytes())?; // reserved
    out.write_all(&1u16.to_le_bytes())?; // type = 1 (icon)
    out.write_all(&count.to_le_bytes())?; // image count

    // Directory entries — offsets computed by accumulating blob lengths
    // starting right after the directory.
    let mut data_offset: u32 = header_size;
    for (size, data) in &encoded {
        // Widths/heights of exactly 256 are stored as 0 in the 1-byte field.
        let wh = if *size == 256 { 0 } else { *size as u8 };
        out.write_all(&[wh])?;                       // width
        out.write_all(&[wh])?;                       // height
        out.write_all(&[0u8])?;                      // color count (0 for >8 bpp)
        out.write_all(&[0u8])?;                      // reserved
        out.write_all(&1u16.to_le_bytes())?;         // color planes
        out.write_all(&32u16.to_le_bytes())?;        // bits per pixel
        out.write_all(&(data.len() as u32).to_le_bytes())?; // data size
        out.write_all(&data_offset.to_le_bytes())?;  // data offset
        data_offset += data.len() as u32;
    }

    // Image blobs (order matches directory).
    for (_, data) in &encoded {
        out.write_all(data)?;
    }

    std::fs::write(path, out.into_inner())
        .with_context(|| format!("write ico {}", path.display()))?;
    Ok(())
}
